### ISSUE TITLE
Unable to use the latest version of pyarrow with pandas

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/arrow-cpp-feedstock#459]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I can't use the latest version of pyarrow with pandas. There are a various moving parts (pyarrow and pandas, and their respective conda-forge recipe feedstocks). Please let me know if this issue could be better addressed elsewhere.

Here is a reproducible example:

```sh
mamba create -n pyarrow-latest -y -c conda-forge --override-channels pandas pyarrow
conda activate pyarrow-latest
python --version

# Able to import pyarrow
python -c "import pyarrow; print(pyarrow.__version__)"

# Unable to export to parquet
python -c "import pandas as pd; pd.DataFrame({'a': [1]}).to_parquet('/tmp/tmp.parquet')"

# Unable to import pyarrow after pandas
python -c "import pandas; import pyarrow; print(pyarrow.__version__)"

conda deactivate
```

Here's the full error message from pandas when failing to run `to_parquet`:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/redacted/mambaforge/envs/pyarrow-latest/lib/python3.9/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/redacted/mambaforge/envs/pyarrow-latest/lib/python3.9/site-packages/pandas/core/frame.py", line 2455, in to_parquet
    return to_parquet(
  File "/redacted/mambaforge/envs/pyarrow-latest/lib/python3.9/site-packages/pandas/io/parquet.py", line 386, in to_parquet
    impl = get_engine(engine)
  File "/redacted/mambaforge/envs/pyarrow-latest/lib/python3.9/site-packages/pandas/io/parquet.py", line 36, in get_engine
    raise ImportError(
ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
```

Here's the full error message from importing pyarrow after pandas:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/redacted/mambaforge/envs/pyarrow-latest/lib/python3.9/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
ImportError: /redacted/GCCcore/6.3.0/lib64/libgcc_s.so.1: version `GCC_7.0.0' not found (required by /redacted/mambaforge/envs/pyarrow-latest/lib/python3.9/site-packages/pyarrow/../../../libarrow.so.400)
```

<br/>
Environment (<code>conda list -n pyarrow-latest</code>):
<details>

```
$ conda list -n pyarrow-latest
# packages in environment at /redacted/mambaforge/envs/pyarrow-latest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
arrow-cpp                 4.0.1           py39h96e570c_1_cpu    conda-forge
aws-c-cal                 0.5.10               h95a6274_1    conda-forge
aws-c-common              0.6.2                h7f98852_0    conda-forge
aws-c-event-stream        0.2.7               h211b232_12    conda-forge
aws-c-io                  0.10.4               h72290dd_0    conda-forge
aws-checksums             0.1.11               ha31a3da_7    conda-forge
aws-sdk-cpp               1.8.186              hb4091e7_3    conda-forge
brotli                    1.0.9                h9c3ff4c_4    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py39hf3d152e_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.5.0                h48cff8f_0    conda-forge
grpc-cpp                  1.38.0               h36ce80c_2    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libprotobuf               3.16.0               h780b84a_0    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libthrift                 0.14.1               he6d91bd_1    conda-forge
libutf8proc               2.6.1                h7f98852_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.20.3           py39hdbf815f_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
orc                       1.6.8                h58a87f1_0    conda-forge
pandas                    1.2.4            py39hde0f152_0    conda-forge
parquet-cpp               1.5.1                         1    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pyarrow                   4.0.1           py39h3ebc44c_1_cpu    conda-forge
python                    3.9.4           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
re2                       2021.06.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
s2n                       1.0.10               h9b69904_0    conda-forge
setuptools                49.6.0           py39hf3d152e_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```
</details>

Note that the pyarrow integration  with pandas works fine with pyarrow 0.17.1:

```sh
mamba create -n pyarrow-legacy -y -c conda-forge --override-channels pandas pyarrow=0.17
conda activate pyarrow-legacy
python -c "import pandas as pd; pd.DataFrame({'a': [1]}).to_parquet('/tmp/tmp.parquet')"
conda deactivate
```

<br/>
Environment (<code>conda list -n pyarrow-legacy</code>):
<details>

```
$ conda list -n pyarrow-legacy
# packages in environment at /redacted/mambaforge/envs/pyarrow-legacy:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20210324.1           h9c3ff4c_0    conda-forge
arrow-cpp                 0.17.1          py39hc046a4d_33_cpu    conda-forge
aws-c-cal                 0.5.10               h95a6274_1    conda-forge
aws-c-common              0.6.2                h7f98852_0    conda-forge
aws-c-event-stream        0.2.7               h211b232_12    conda-forge
aws-c-io                  0.10.4               h72290dd_0    conda-forge
aws-checksums             0.1.11               ha31a3da_7    conda-forge
aws-sdk-cpp               1.8.186              hb4091e7_3    conda-forge
boost-cpp                 1.74.0               hc6e9bd1_3    conda-forge
brotli                    1.0.9                h9c3ff4c_4    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py39hf3d152e_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.5.0                h48cff8f_0    conda-forge
grpc-cpp                  1.37.1               h2519f57_2    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libprotobuf               3.16.0               h780b84a_0    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libthrift                 0.14.1               he6d91bd_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.20.3           py39hdbf815f_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
orc                       1.6.7                h89a63ab_2    conda-forge
pandas                    1.2.4            py39hde0f152_0    conda-forge
parquet-cpp               1.5.1                         1    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pyarrow                   0.17.1          py39hbbe4ea4_33_cpu    conda-forge
python                    3.9.4           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
re2                       2021.04.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
s2n                       1.0.10               h9b69904_0    conda-forge
setuptools                49.6.0           py39hf3d152e_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : base
    active env location : /redacted/mambaforge
            shell level : 1
       user config file : /redacted/.condarc
 populated config files : /redacted/mambaforge/.condarc
                          /redacted/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.9.4.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /redacted/mambaforge  (writable)
      conda av data dir : /redacted/mambaforge/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /redacted/mambaforge/pkgs
                          /redacted/.conda/pkgs
       envs directories : /redacted/mambaforge/envs
                          /redacted/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.9.4 Linux/3.10.0-1062.12.1.el7.x86_64 centos/7.7.1908 glibc/2.17
                UID:GID : 2008801:1950
             netrc file : None
           offline mode : False

```
</details>

**Comment by xhochy** [comment]
@jdblischak Is `/redacted/GCCcore/6.3.0/lib64/libgcc_s.so.1:` part of the conda environment?

**Comment by jdblischak** [comment]
> /redacted/GCCcore/6.3.0/lib64/libgcc_s.so.1: part of the conda environment?

No. It is some system-wide installation. I am pretty sure it is loaded by an environment module. 

The paths with `mambaforge` point to the conda environments. These are in my home directory, so could also be written `~/mambaforge/envs/pyarrow-latest/` and `~/mambaforge/envs/pyarrow-legacy/`.

**Comment by jdblischak** [comment]
Purging the environment modules fixes the issue:

```sh
module purge
conda activate pyarrow-latest
python -c "import pandas; import pyarrow; print(pyarrow.__version__)"
python -c "import pandas as pd; pd.DataFrame({'a': [1]}).to_parquet('/tmp/tmp.parquet')"
```

But I'm confused why I have to do this. pyarrow 0.17.1 was unaffected by the environment modules. Also, why would importing pandas change where pyarrow looks for libgcc?

**Comment by jdblischak** [comment]
I've continued to investigate. Looking at `PATH`, I confirmed that the first two entries are `~/mambaforge/envs/pyarrow-latest/bin` and `~/mambaforge/condabin`. The problematic path, `/redacted/GCCcore/6.3.0/bin`, is much later in the `PATH`. Thus if pyarrow needs libgcc, why can't it find it first in the conda environment?

**Comment by jdblischak** [comment]
The change in behavior was introduced between pyarrow 2.0.0 and pyarrow 3.0.0. I looked at the change log and didn't see anything obvious (to me at least) that would affect libgcc.

https://github.com/conda-forge/arrow-cpp-feedstock/compare/2.0.x...3.0.x

```sh
# works
mamba create -n pyarrow-test -y -c conda-forge --override-channels pandas pyarrow=2.0
conda activate pyarrow-test
python --version
python -c "import pyarrow; print(pyarrow.__version__)"
python -c "import pandas as pd; pd.DataFrame({'a': [1]}).to_parquet('/tmp/tmp.parquet', engine='pyarrow')"
python -c "import pandas; import pyarrow; print(pyarrow.__version__)"
conda deactivate

# fails
mamba create -n pyarrow-test -y -c conda-forge --override-channels pandas pyarrow=3.0
conda activate pyarrow-test
python --version
python -c "import pyarrow; print(pyarrow.__version__)"
python -c "import pandas as pd; pd.DataFrame({'a': [1]}).to_parquet('/tmp/tmp.parquet', engine='pyarrow')"
python -c "import pandas; import pyarrow; print(pyarrow.__version__)"
conda deactivate
```

Both of the above use the same Python (3.9.4) and pandas (1.2.4).

**Comment by jdblischak** [comment]
I confirmed today that this issue persists. pyarrow 3+ is unable to find libgcc in the conda environment, and instead tries to import `libgcc_s.so.1` from a later path in `PATH`. pyarrow 2.0.0 does not have this issue.

```sh
mamba create -n pyarrow-test -y -c conda-forge --override-channels pandas pyarrow=5.0
conda activate pyarrow-test
conda list arrow
# packages in environment at ~/mambaforge/envs/pyarrow-test:
#
# Name                    Version                   Build  Channel
# arrow-cpp                 5.0.0           py39he92c077_3_cpu    conda-forge
# pyarrow                   5.0.0           py39h3ebc44c_3_cpu    conda-forge
python -c "import pandas; import pyarrow; print(pyarrow.__version__)"
conda deactivate
conda env remove -n pyarrow-test
```


```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/mambaforge/envs/pyarrow-test/lib/python3.9/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
ImportError: /redacted/GCCcore/6.3.0/lib64/libgcc_s.so.1: version `GCC_7.0.0' not found (required by ~/mambaforge/envs/pyarrow-test/lib/python3.9/site-packages/pyarrow/../../../libarrow.so.500)
```

**Comment by cfilleke** [comment]
@jdblischak how did you solve this?

**Comment by jdblischak** [comment]
> how did you solve this?

@cfilleke My workaround was to pin pyarrow to 2.0 in my environment file with `pyarrow=2.0`.

I still have the old environments available, and thus I can still reproduce the error:

```sh
conda activate pyarrow-legacy
python -c "import pandas; import pyarrow; print(pyarrow.__version__)"
## 0.17.1
conda deactivate

conda activate pyarrow-latest
python -c "import pandas; import pyarrow; print(pyarrow.__version__)"
## Traceback (most recent call last):
##   File "<string>", line 1, in <module>
##   File "~/mambaforge/envs/pyarrow-latest/lib/python3.9/site-packages/pyarrow/__init__.py", line 63, in <module>
##     import pyarrow.lib as _lib
## ImportError: /readacted/GCCcore/6.3.0/lib64/libgcc_s.so.1: version `GCC_7.0.0' not found (required by ~/mambaforge/envs/pyarrow-latest/lib/python3.9/site-packages/pyarrow/../../../libarrow.so.400)
conda deactivate
```

However, some dependency has changed such that this is no longer an issue. Now if I install pyarrow 5.0, even if I specify python=3.9 and pandas=1.2.4, it works:

```sh
mamba create -n pyarrow-test -y -c conda-forge --override-channels python=3.9 pandas=1.2.4 pyarrow=5.0
conda activate pyarrow-test
conda list arrow
## packages in environment at ~/mambaforge/envs/pyarrow-test:
##
## Name                    Version                   Build  Channel
## arrow-cpp                 5.0.0           py39he2ccf02_29_cpu    conda-forge
## pyarrow                   5.0.0           py39h42d110c_29_cpu    conda-forge
python -c "import pandas; import pyarrow; print(pyarrow.__version__)"
## 5.0.0
conda deactivate
conda env remove -n pyarrow-test
```

<details>
<summary><code>conda list -n pyarrow-test</code>
</summary>

```sh
# packages in environment at ~/mambaforge/envs/pyarrow-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20211102.0           h27087fc_1    conda-forge
arrow-cpp                 5.0.0           py39he2ccf02_29_cpu    conda-forge
aws-c-cal                 0.5.11               h95a6274_0    conda-forge
aws-c-common              0.6.2                h7f98852_0    conda-forge
aws-c-event-stream        0.2.7               h3541f99_13    conda-forge
aws-c-io                  0.10.5               hfb6a706_0    conda-forge
aws-checksums             0.1.11               ha31a3da_7    conda-forge
aws-sdk-cpp               1.8.186              hb4091e7_3    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
grpc-cpp                  1.45.1               h3d78c48_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           14_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0           14_linux64_openblas    conda-forge
libcurl                   7.82.0               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_15    conda-forge
libgfortran-ng            11.2.0              h69a702a_15    conda-forge
libgfortran5              11.2.0              h5c6108e_15    conda-forge
libgomp                   11.2.0              h1d223b6_15    conda-forge
liblapack                 3.9.0           14_linux64_openblas    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libprotobuf               3.19.4               h780b84a_0    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_15    conda-forge
libthrift                 0.16.0               h519c5ea_1    conda-forge
libutf8proc               2.7.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.22.3           py39h18676bf_2    conda-forge
openssl                   1.1.1n               h166bdaf_0    conda-forge
orc                       1.7.3                h1be678f_0    conda-forge
pandas                    1.2.4            py39hde0f152_0    conda-forge
parquet-cpp               1.5.1                         1    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pyarrow                   5.0.0           py39h42d110c_29_cpu    conda-forge
python                    3.9.12          h9a8a25e_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
re2                       2022.02.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
s2n                       1.0.10               h9b69904_0    conda-forge
setuptools                59.8.0           py39hf3d152e_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.38.2               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

</details>
So my current advice is the following:

1. If you're maintaining a legacy environment with older builds, pin `pyarrow=2.0`
2. If you are free to update, update all of your conda-forge packages to the latest version to see if that fixes it

If you're still getting this error after updating your conda environment, please share `conda list` (or even better: `conda list --export`). For the sake of posterity, I've exported my old environments that reproduce this error (annoyingly GitHub doesn't allow the file extension `.yaml`, as if this is materially different than `.txt`):

* [pyarrow-legacy.txt](https://github.com/conda-forge/arrow-cpp-feedstock/files/8522821/pyarrow-legacy.txt) - pyarrow 0.17.1 does not have the error
* [pyarrow-latest.txt](https://github.com/conda-forge/arrow-cpp-feedstock/files/8522826/pyarrow-latest.txt) - pyarrow 4.0.1 reproduces the error (it was the latest version when I originally opened this issue)

Here's how to reproduce it:

```sh
conda create -n pyarrow-reproduce --file pyarrow-latest.txt
conda activate pyarrow-reproduce
## Traceback (most recent call last):
##   File "<string>", line 1, in <module>
##   File "~/mambaforge/envs/pyarrow-reproduce/lib/python3.9/site-packages/pyarrow/__init__.py", line 63, in <module>
##     import pyarrow.lib as _lib
## ImportError: /redacted/GCCcore/6.3.0/lib64/libgcc_s.so.1: version `GCC_7.0.0' not found (required by ~/mambaforge/envs/pyarrow-reproduce/lib/python3.9/site-packages/pyarrow/../../../libarrow.so.400)
conda deactivate
conda env remove -n pyarrow-reproduce
```

**Comment by cfilleke** [comment]
Thanks @jdblischak -- I managed to build & install v 7 pyarrow in a container, and install it to be used with Anaconda python.  This isn't supposed to be possible, but it works.  Needed to build pyarrow from scratch because there's no conda or pip pre-built for it on the s390x architecture.
