### ISSUE TITLE
newly released libthrift-0.14.2 renders pyarrow unusable

### ISSUE THREAD

**Issue by achimgaedke** [conda-forge/arrow-cpp-feedstock#461]
After reinstalling a previously working conda environment,  I ran into this error using `pandas.read_parquet`
```
Traceback (most recent call last):
  File "/notebooks/xxxx/tests.py", line 35, in test_xxxx
[....]
  File "/notebooks/achim/.conda/envs/po-achim/lib/python3.9/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/notebooks/achim/.conda/envs/po-achim/lib/python3.9/site-packages/pandas/core/frame.py", line 2455, in to_parquet
    return to_parquet(
  File "/notebooks/achim/.conda/envs/po-achim/lib/python3.9/site-packages/pandas/io/parquet.py", line 386, in to_parquet
    impl = get_engine(engine)
  File "/notebooks/achim/.conda/envs/po-achim/lib/python3.9/site-packages/pandas/io/parquet.py", line 36, in get_engine
    raise ImportError(
ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - libthrift.so.0.14.1: cannot open shared object file: No such file or directory
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
 ```

The environment contains pandas 1.2.4 and pyarrow 4.0.1. This failure is reproduced on MacOS and Linux.

The same error occurred when trying to use the pyarrow engine parquet IO with pandas directly.
Here for MacOS:
```
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas.io.parquet
>>> pandas.io.parquet.PyArrowImpl()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/xxxx/lib/python3.9/site-packages/pandas/io/parquet.py", line 129, in __init__
    import pyarrow.parquet
  File "/usr/local/Caskroom/miniconda/base/envs/xxxx/lib/python3.9/site-packages/pyarrow/parquet.py", line 33, in <module>
    import pyarrow._parquet as _parquet
ImportError: dlopen(/usr/local/Caskroom/miniconda/base/envs/xxx/lib/python3.9/site-packages/pyarrow/_parquet.cpython-39-darwin.so, 2): Library not loaded: @rpath/libthrift.0.14.1.dylib
  Referenced from: /usr/local/Caskroom/miniconda/base/envs/xxxlib/libparquet.400.0.0.dylib
  Reason: image not found
>>> 
```

As a temporary solution, I added `libthrift=0.14.1` to my conda environment file and pandas/pyarrow resume working fine.

**Comment by arthurp** [comment]
There failures also appear here: https://github.com/conda-forge/arrow-cpp-feedstock/pull/464

(And I'm running into this in my company's CI. I'm sure it will pop up in our open-source CI soon enough: https://github.com/KatanaGraph/katana)

**Comment by arthurp** [comment]
libthrift has fixed the underlying issue that caused this in https://github.com/conda-forge/thrift-cpp-feedstock/commit/136cbf12c1c3d1990a69fc361cc14e4b633712c8. So I think rebuilding arrow-cpp with the correct upstream package verisons should be all that's needed. (Pinnings may need to be changed.)

**Comment by achimgaedke** [comment]
Thanks @arthurp and others!

I'll wait a day till "the universe fixed itself".

**Comment by xhochy** [comment]
We have fixed this via repodata patching https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/145 and the issue in the CI build should be fixed by migrating to a newer `libthrift`.
